---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: mini-visa
data:
  # Application configuration
  PORT: "8080"
  THREADS: "8"
  QUEUE_CAP: "2048"
  LOG_LEVEL: "INFO"
  
  # Service URLs (internal cluster communication)
  RISK_SERVICE_URL: "http://risk-service:8081"
  CLEARING_SERVICE_URL: "http://clearing-service:8082"
  LEDGER_SERVICE_URL: "http://ledger-service:8083"
  
  # Timeouts (milliseconds)
  HTTP_CLIENT_TIMEOUT: "3000"
  DB_CONNECTION_TIMEOUT: "5000"
  
  # Circuit Breaker Configuration
  CB_FAILURE_THRESHOLD: "5"
  CB_RECOVERY_TIMEOUT: "30"
  CB_REQUEST_VOLUME_THRESHOLD: "20"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Business Logic
  MAX_TRANSACTION_AMOUNT: "10000.00"
  IDEMPOTENCY_TTL_HOURS: "24"