---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: mini-visa
  labels:
    app: payment-service
    service: payment-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-external
  namespace: mini-visa
  labels:
    app: payment-service
    service: payment-service-external
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
# Headless service for StatefulSet scenarios (if needed)
apiVersion: v1
kind: Service
metadata:
  name: payment-service-headless
  namespace: mini-visa
  labels:
    app: payment-service
    service: payment-service-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: payment-service