name: CD Staging

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

      - name: Deploy to staging via SSH
        if: ${{ secrets.STAGING_HOST && secrets.STAGING_USER && secrets.STAGING_SSH_KEY && secrets.STAGING_DB_URI }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            set -euo pipefail
            docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            docker rm -f mini-visa || true
            docker run -d --name mini-visa --restart=always \
              -e DB_URI='${{ secrets.STAGING_DB_URI }}' -e PORT=9090 \
              -p 9090:9090 ghcr.io/${{ github.repository }}:${{ github.sha }}

